export default {
    'logo': 'insistime.com',
    'github': 'Github',
    'githubUrl': 'https://github.com/uikoo9/qiao-monorepo',
    'webTitle': '网页开发',
    'webDesc': 'PC浏览器网页开发 手机H5页面开发',
    'wechatTitle': '微信开发',
    'wechatDesc': '微信公众号开发 微信小程序开发',
    'adminTitle': '管理系统开发',
    'adminDesc': '各种管理系统开发',
    'electronTitle': '桌面应用开发',
    'electronDesc': 'windows桌面应用开发 mac桌面应用开发',
    'appTitle': 'APP开发',
    'appDesc': 'iOS APP开发 Android APP开发',
    'otherTitle': '其他服务',
    'otherDesc': '域名注册 服务器部署等',
    'insistime': 'insistime.com',
    'insistimeSolgan': '坚持，时机，创造，热爱',
    'insistimeUrl': 'https://insistime.com/',
    'beian': '京ICP备18041615号-1',
    'beianUrl': 'https://beian.miit.gov.cn/',

};